### ISSUE TITLE
Pathfinder JS SDK

### ISSUE THREAD

**Issue by grovecj** [CSSE497/pathfinder.js#1]
Create an SDK that allows JS developers to use our service  
- [x] can create commodity  
- [x] can cancel commodity  
- [x] can receive vehicle updates  
- [x] can receive commodity updates  
- [x] can receive route updates  
- [x] can query clusters

**Comment by grovecj** [comment]
Week 1 Time: 4 hours

**Comment by robinsdm** [comment]
@grovecj I changed the "email" in the create application request to "username".

**Comment by robinsdm** [comment]
This should be done now.
