### ISSUE TITLE
JavaScript SDK Feedback

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder.js#3]
- [ ] Callbacks Removed
- [ ] Uses promises or RxJS  
- [ ] Add vehicle class

**Comment by grovecj** [comment]
@aj-michael @robinsdm 

My understanding of promises is that once they have been settled (fulfilled or rejected), they remain in that state. So, if you do something like:

```
cluster.cluterWasRouted().then(function(response) {}, function(err) {});
```

you are S.O.L. if you get rerouted again unless you create another promise. I think it still makes sense to use promises for things like clusterById, but for push notifications which the server may call multiple times, it still seems appropriate to use callbacks. Does this seem reasonable or am I not seeing something?

**Comment by aj-michael** [comment]
@grovecj after talking with mike, he agrees with you. We have removed all promises.
