### ISSUE TITLE
Pathfinder api cannot handle reqests made before socket finishes opening

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder.js#7]
any messages sent when the socket is not opened are ignored. This includes messages sent right after a pathfinder instance is instantiated when the websocket is in the process of opening. Instead, whenever a message request is attempted to be sent, the api should:
- [x] If the socket is not ready, save the message and send it once the socket is opened
- [x] Should handle multiple messages made before the socket is opened
- [x] Messages should be sent in same order they are made in once the socket is opened
- [x] If the socket is closed when a message is sent, it should probably print a readable error message, alternatively, the api could try to open a new socket if it is closed, but that requires more work and probably is unnecessary

**Comment by danhanson** [comment]
I think I mostly fixed it in https://github.com/CSSE497/pathfinder.js/tree/fixed-bugs which is based off of the edits I used to get the chimney swap website to work, but you should make sure that it works and fix it if it doesn't

**Comment by aj-michael** [comment]
@danhanson , if you want the code to be updated, you need to open a pull request.

**Comment by robinsdm** [comment]
@danhanson I pulled the code. Can you update the check off list.

**Comment by danhanson** [comment]
Ok
