### ISSUE TITLE
Some functions use bind incorrectly within Commodity.js and Cluster.js

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder.js#8]
In the api, methods that are defined like this don't do anything when called

```
Constructor.prototype.method = function(/* paramters */){
    this.pathfinder.helper(/* arguments */).bind(this.pathfinder);
}
```

I think you have meant to do this:

```
Constructor.prototype.method = function(/* paramters */){
    this.pathfinder.helper(/* arguments */);
}
```

If you were trying to make sure if only the version of the method defined in the pathfinder prototype is used(which is technically safer but probably unnecessary). You could do it like this.

```
Constructor.prototype.method = function(/* paramters */){
    Pathfinder.prototype.helper.call(this.pathfinder, /* arguments */);
}
```

I fixed most of these in the fixed-bugs branch I think: https://github.com/CSSE497/pathfinder.js/tree/fixed-bugs

**Comment by robinsdm** [comment]
It was to make sure the "this" context is set to pathfinder when the function is called. So that it doesn't create problems with "this" referring to the wrong object.

**Comment by aj-michael** [comment]
Did we ever resolve this?

**Comment by robinsdm** [comment]
I think Dan made a fix for this and I pulled it.
